### ISSUE TITLE
QC rules

### ISSUE THREAD

**Issue by kaitj** [khanlab/scattr#54]
Add some rules to perform QC for the workflow. QCs may involve the following:
- [x] Accuracy of segmentations (e.g. approproriate coverage of structures)

**Comment by tkkuehn** [comment]
Goal is to get a minimal implementation of this ready in the next week or two. Features:

- Having the registrations would be helpful
- Want to see the segmentations overlaid on the actual image, because this can have a big impact on the downstream results.

**Comment by kaitj** [comment]
The wip process branch is in @arunthurai repo? Did you want me to tackle this or did you want the first crack @tkkuehn ?

**Comment by kaitj** [comment]
> If you have the time for it I'm happy to give you the first crack at it

Sounds good - I should have some time later this week to give it a go
