### ISSUE TITLE
Don't warn about missing DWIs if --dwi_dir is given

### ISSUE THREAD

**Issue by tkkuehn** [khanlab/scattr#84]
## The problem

If `--dwi_dir` is passed on the command line, we don't expect to find any DWIs in the `bids_dir`. We still warn though, so it would be nice to suppress that warning somehow. https://github.com/akhanf/snakebids/issues/293 will help with this.

**Comment by kaitj** [comment]
Just to add a note (and may be better for a separate issue), but we should update to be able to handle different naming schemes (re: see [changes](https://github.com/akhanf/scattr/commit/20f91b9f8ef416a3725594867348e8ff9ba673fe) for to handle snakedwi).
